/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qxjotyjqhoidoshdoxmo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4am90eWpxaG9pZG9zaGRveG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5OTY0NTEsImV4cCI6MjA5MzU3MjQ1MX0.U0J4pixPm8jNimmstgyQDSZ1kE9nv-iB-XAR8OiInI0"